<?php

namespace App\Support;

/**
 * Reads one release's notes out of CHANGELOG.md.
 *
 * The changelog is generated by release-please, so its shape is predictable:
 * one `## [x.y.z](compare-url) (date)` heading per release, and everything up
 * to the next `##` belongs to it.
 *
 * Parsing it locally means a deployed instance can answer "what shipped in the
 * version I am running" without reaching GitHub -- which is exactly when you
 * want the answer, because the deploy looks wrong and you are deciding whether
 * to roll back.
 */
class ReleaseNotes
{
    public function __construct(private readonly string $path)
    {
    }

    /** The changelog shipped with this build. */
    public static function default(): self
    {
        return new self((string) config('version.changelog'));
    }

    public function exists(): bool
    {
        return is_file($this->path);
    }

    /**
     * Every version the changelog documents, newest first.
     *
     * File order, not sorted: release-please writes newest at the top, and
     * trusting that is better than trying to version-sort strings that may
     * carry prerelease suffixes.
     *
     * @return list<string>
     */
    public function versions(): array
    {
        return array_keys($this->sections());
    }

    /**
     * The notes for one version, or null when the changelog has no such entry.
     *
     * A leading `v` is accepted so a tag name can be passed straight through.
     */
    public function for(string $version): ?string
    {
        return $this->sections()[self::normalise($version)] ?? null;
    }

    /**
     * Split the changelog into version => notes.
     *
     * Only `##` headings start a section, so the `###` subheadings
     * release-please emits for Features and Bug Fixes stay inside the release
     * they belong to. Anything before the first `##` -- the `# Changelog`
     * title -- belongs to no release and is dropped.
     *
     * @return array<string, string>
     */
    private function sections(): array
    {
        if (! $this->exists()) {
            return [];
        }

        $sections = [];
        $current = null;

        foreach (preg_split('/\R/', (string) file_get_contents($this->path)) as $line) {
            if (preg_match('/^##\s+\[?v?(\d+\.\d+\.\d+[^\]\s]*)\]?/', $line, $matches) === 1) {
                $current = $matches[1];
                $sections[$current] = '';

                continue;
            }

            if ($current !== null) {
                $sections[$current] .= $line."\n";
            }
        }

        return array_map(trim(...), $sections);
    }

    private static function normalise(string $version): string
    {
        return ltrim(trim($version), 'vV');
    }
}
